backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
# This line should *not* be indented
media_folder: "images/gallery" # Media files will be stored in the repo under images/gallery

collections:
  - name: "gallery" # Used in routes
    label: "GalleryItem" # Used in the UI
    folder: "/paintings" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Dimensions", name: "dimensions", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}